# Generated by Django 5.0.4 on 2024-05-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
